# 1 Create 1D,2D,3D array . check it’s shape and dimension


In [1]:
import numpy as np 

In [5]:
a=np.array([2,8,7,4])
b=np.array([[1,4,3],[4,8,6]])
c=np.array([[[1,9,3],[4,45,6]],[[53,2,13],[6,5,4]],[[7,12,9],[9,10,7]]])
print(a.shape,a.ndim)
print(b.shape,b.ndim)
print(c.shape,c.ndim)

(4,) 1
(2, 3) 2
(3, 2, 3) 3


# 2. Create a NumPy array of numbers from 10 to 50 (inclusive) with a step of 5.

In [6]:
np.arange(10,51,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

# 3.Generate a 3×3 matrix of random integers between 1 and 20.

In [13]:
matrix=np.random.randint(1,21,(3,3))
print(matrix)

[[19 12 18]
 [ 5 15  9]
 [19 20 17]]


# 4.Form the array:

# a.Extract the second row.

In [18]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1])

[4 5 6]


# b.Extract the first column.

In [22]:
print(arr[:,0])

[1 4 7]


# c.Extract the subarray containing rows 1–2 and columns 2–4c

In [23]:
print(arr[1:3,1:3])

[[5 6]
 [8 9]]


# d.Replace all even numbers in arr with -1


In [24]:
arr[arr%2==0]=-1
print(arr)

[[ 1 -1  3]
 [-1  5 -1]
 [ 7 -1  9]]


# 5 given:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

Perform element-wise addition, subtraction, multiplication, and division.
Create a 1D array of numbers from 1 to 12. Reshape it into:  3×4 matrix

In [26]:


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


# creat 1D  array of numbers from 1 to 12 .reshape it into 3*4 matrix

In [36]:
m=np.array([1,22,33,54,45,26,57,8,95,80,91,92])
m.reshape(3,4)

array([[ 1, 22, 33, 54],
       [45, 26, 57,  8],
       [95, 80, 91, 92]])